version: '3'
services:
  Rproxy:
    container_name: Rproxy_con
    image: Rproxy
    volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
            - "80:80"
networks:
    default:
       external:
          name: network